name: flutter_auth
description: Flutter plugin for seemless auth module integration.
version: 1.9.1
homepage: https://github.com/kaushalkaajtak/flutter_auth

environment:
  sdk: ">=2.19.1 <=3.13.2"
  flutter: ">=2.5.0"

dependencies:
  url_launcher: ^6.1.11
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.3
  provider: ^6.0.5

  # http request
  dio: ^5.3.3

  # for equality check
  equatable: ^2.0.5

  # dependency injection
  get_it: ^7.2.0

  # for authenticatio package
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  plugin_platform_interface: ^2.0.2
  sign_in_with_apple: ^5.0.0

  # for device identifier
  device_info_plus: ^9.1.0

  pin_code_fields: ^8.0.1

  country_picker: ^2.0.22

  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner:
  flutter_gen_runner:

# for generating assets class
flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/gen/

flutter:
  plugin:
    platforms:
      android:
        package: com.aajtak.flutter_auth
        pluginClass: FlutterAuthPlugin
      ios:
        pluginClass: FlutterAuthPlugin

  # adding assets
  assets:
    - assets/icons/
